version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ECR_ACCOUNT: 448049808053
    REPO_NAME: dotnet-sample
    REPO_URI: $ECR_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME
    IMAGE_TAG: $CODEBUILD_BUILD_NUMBER

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - apt-get update -y
      - apt-get install -y docker.io
      - dotnet --info
      - docker run --privileged --rm tonistiigi/binfmt --install all
      - mkdir -p ~/.docker/cli-plugins
      - curl -fsSL https://github.com/docker/buildx/releases/download/v0.10.5/buildx-v0.10.5.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
      - chmod +x ~/.docker/cli-plugins/docker-buildx
      - export DOCKER_BUILDKIT=1

  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPO_URI

  build:
    commands:
      - dotnet restore
      - dotnet publish -c Release -p:ContainerRegistry=$REPO_URI -p:ContainerImageTag=$IMAGE_TAG -p:ContainerRuntimeIdentifiers="linux-x64;linux-arm64" /t:PublishContainer --no-restore
